on: [pull_request]

jobs:
  check-properties:
    runs-on: ubuntu-latest
    name: Testing properties
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Error 500 Demo
        run: |
          text="This is an Error"
          echo "::error file=francais,line=3,col=1::$text"
